name: spiraw
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  path_provider:
  intl:
  shared_preferences:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  connectivity_plus:
  google_fonts:
  flutter_picker:
  url_launcher:
  flutter_inset_box_shadow:
  mask_text_input_formatter:
  pin_code_fields:
  flutter_dash:
  material_symbols_icons:


  outline_gradient_button:
  dotted_border:


  glassmorphism: ^3.0.0
  gap: ^3.0.1
  action_slider: ^0.7.0
  simple_circular_progress_bar:
  vertical_percent_indicator: ^0.0.1
  flutter_time_picker_spinner: ^2.0.0
  flutter_spinner_picker: ^0.0.7
  day_picker: ^2.2.0
  qr_code_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400

    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
