// export '../modules/auth/email_signup/module/email_signup_module.dart';
// export '../modules/auth/otp/module/otp_module.dart';
// export '../modules/auth/phone_signup/module/phone_signup_module.dart';
export '../modules/auth/login/module/login_module.dart';
export '../modules/auth/signup/module/signup_module.dart';
export '../modules/design_sytem/ds_module.dart';
export '../modules/splash/splash_module.dart';
// export '../modules/auth/user_info/module/user_info_module.dart';
// export '../modules/core/emergency_calling/module/emergency_calling_module.dart';
// export '../modules/core/sos_text_message/stay_connected/module/stay_connected_module.dart';
// export '../modules/core/sos_text_message/text_message_setup/module/message_setup_module.dart';
// export 'core/menu/menu_bindings.dart';
// export 'core/setup/setup_module.dart';
