export '../modules/after_splash/module/after_splash_module.dart';
export '../modules/auth/login/module/login_module.dart';
export '../modules/auth/otp/module/otp_module.dart';
export '../modules/auth/phone_login/module/phone_login_module.dart';
export '../modules/auth/signup/module/signup_module.dart';
export '../modules/auth/user_info/module/user_info_module.dart';
export '../modules/auth_machine/modules/get_started_module.dart';
export '../modules/auth_machine/modules/scanner_module.dart';
export '../modules/auth_machine/modules/success_module.dart';
export '../modules/core/machine_setup/modules/add_water_module.dart';
export '../modules/core/machine_setup/modules/disinfection_module.dart';
export '../modules/core/machine_setup/modules/disinfection_success_module.dart';
export '../modules/core/machine_setup/modules/scanning_starter_module.dart';
export '../modules/core/machine_setup/modules/scanning_supplement_module.dart';
export '../modules/core/machine_setup/modules/scanning_template_module.dart';
export '../modules/core/machine_setup/modules/starter_added_module.dart';
export '../modules/core/machine_setup/modules/success_template_module.dart';
export '../modules/core/machine_setup/modules/supplement_added_module.dart';
export '../modules/core/machine_setup/modules/well_done_module.dart';
export '../modules/design_sytem/ds_module.dart';
export '../modules/splash/splash_module.dart';
export 'core/community_home_page/add_recipe/modules/add_ingredients_module.dart';
export 'core/community_home_page/add_recipe/modules/add_recipe_module.dart';
export 'core/community_home_page/add_recipe/modules/ingredients_after_add_module.dart';
export 'core/community_home_page/add_recipe/modules/ingredients_module.dart';
export 'core/community_home_page/add_recipe/modules/recipe_categories_module.dart';
export 'core/community_home_page/add_recipe/modules/time_spent_module.dart';
export 'core/community_home_page/recipe_page/module/recipe_page_module.dart';
export 'core/machine_home_page/eco_impact/modules/eco_impact_module.dart';
export 'core/machine_home_page/modules/machine_home_page_module.dart';
export 'core/machine_home_page/modules/schedule_time_module.dart';
export 'core/machine_home_page/spirulina_growth/modules/spirulina_growth_module.dart';
// export '../modules/core/emergency_calling/module/emergency_calling_module.dart';
// export '../modules/core/sos_text_message/stay_connected/module/stay_connected_module.dart';
// export '../modules/core/sos_text_message/text_message_setup/module/message_setup_module.dart';
// export 'core/menu/menu_bindings.dart';
// export 'core/setup/setup_module.dart';
